import Head from 'next/head'
import { Inter } from 'next/font/google'

import Header from '../components/Header'
import Button from '../components/Button'
import ListeProduits from '../components/ListeProduits'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Agriculture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
      <Header urlBackground='./assets/home/Banner.png'/>
      <section className='py-28 section'>
        <div className='mx-52 flex justify-around gap-5'>
          <div className='block'>
            <img src="./assets/home/carrousel_1.png" alt="" />
          </div>
          <div className='block'>
            <img src="./assets/home/carrousel_2.png" alt="" />
          </div>
        </div>
      </section>


      <section className='section relative'>
        <div className='absolute flex justify-end z-10 lg:mx-54 mx-20 right-0'>
          <div className='py-28'>
            <h6 className='grid-cols-2'
              style={{ color: 'var(--color-green)',
              fontSize: 24,
              fontWeight: 'bold',
              fontStyle: 'italic',
              fontFamily: 'Yellowtail'}}>
                About Us</h6>

            <h3 className="font-black pb-3"
            style={{ fontSize: "var(--text-size_h3)", lineHeight: '3rem', maxWidth: '20ch'}}>We Believe in Working Accredited Farmers</h3>

            <p style={{ maxWidth: '60ch' }}>Simply dummy text of the printing and typesetting industry. Lorem had ceased to
            been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>

            <div className='py-6'>
              <div className='flex'>
                <img src="./assets/home/IconFoodBowl.png" alt=""
                  className='p-2'/>
                <div>
                  <h6 className='py-1' style={{ fontSize: "var(--text-size_h6)", fontWeight: 'bold'}}>Organic Foods Only</h6>
                  <p style={{ maxWidth: '40ch'}}>Simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                </div>
              </div>
              <div className='flex'>
              <img src="./assets/home/IconQualityMail.png" alt=""
                className='p-2'/>
                <div>
                  <h6 className='py-1' style={{ fontSize: "var(--text-size_h6)", fontWeight: 'bold'}}>Quality Standards</h6>
                  <p style={{ maxWidth: '40ch'}}>Simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                </div>
              </div>
            </div>
            <Button name='Show now'
              colorBG='var(--color-blueDark)'
              colorTXT='var(--color-grayLight)'/>
          </div>
        </div>
        <img className='relative object-cover ' src="./assets/home/about.png" alt="" />
      </section>

      <section className='section'>
        <div className='mx-52'>
          <header className='flex flex-col items-center pt-28 pb-7'>
            <h6 className=''
              style={{ color: 'var(--color-green)',
              fontSize: 24,
              fontWeight: 'bold',
              fontStyle: 'italic',
              fontFamily: 'Yellowtail'}}>
                Categories</h6>

            <h3 className="font-black pb-3"
              style={{ fontSize: "var(--text-size_h3)", lineHeight: '3rem', maxWidth: '20ch'}}>Our Products</h3>
          </header>
          <ListeProduits />
        </div>
      </section>
      </main>
    </>
  )
}
