import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Agriculture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
      <Header urlBackground='./assets/home/Banner.png'/>

      <section>
        <div className='mx-52 flex'>
          <div>

          </div>
          <div>

          </div>
        </div>
      </section>
      </main>
    </>
  )
}
